module.exports = {
  OK: { statusCode: 200, message: "OK" },
  CREATED: { statusCode: 201, message: "Created" },
  ACCEPTED: { statusCode: 202, message: "Accepted" },
  NO_CONTENT: { statusCode: 204, message: "No Content" },
  MOVED_PERMANENTLY: { statusCode: 301, message: "Moved Permanently" },
  FOUND: { statusCode: 302, message: "Found" },
  SEE_OTHER: { statusCode: 303, message: "See Other" },
  NOT_MODIFIED: { statusCode: 304, message: "Not Modified" },
  USE_PROXY: { statusCode: 305, message: "Use Proxy" },
  TEMPORARY_REDIRECT: { statusCode: 307, message: "Temporary Redirect" },
  PERMANENT_REDIRECT: { statusCode: 308, message: "Permanent Redirect" },
  BAD_REQUEST: { statusCode: 400, message: "Bad Request" },
  UNAUTHORIZED: { statusCode: 401, message: "Unauthorized" },
  FORBIDDEN: { statusCode: 403, message: "Forbidden" },
  NOT_FOUND: { statusCode: 404, message: "Not Found" },
  METHOD_NOT_ALLOWED: { statusCode: 405, message: "Method Not Allowed" },
  CONFLICT: { statusCode: 409, message: "Conflict" },
  INTERNAL_SERVER_ERROR: { statusCode: 500, message: "Internal Server Error" },
  SERVICE_UNAVAILABLE: { statusCode: 503, message: "Service Unavailable" },
};
